[[aws_c_http]]
arch = "aarch64"
git-tree-sha1 = "392ca9aa39fcd5224d27a2fa00ef137ae6f933dd"
os = "macos"

    [[aws_c_http.download]]
    sha256 = "fc1f259c390f9ee38b93f05f9d49bcc2da279d32b733edc0a0e2e40e4cbba5bf"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.10+0/aws_c_http.v0.10.10.aarch64-apple-darwin.tar.gz"
[[aws_c_http]]
arch = "aarch64"
git-tree-sha1 = "0412e8be5aa76d73a0504a2a17668499aeb88392"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "ee67961d84d69d36f4aa3905c9e9cf9a35f74aa26f803ff68524781fa6eb3fe4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.10+0/aws_c_http.v0.10.10.aarch64-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "aarch64"
git-tree-sha1 = "cd0a028a5212846f98cb0d46ee50f32798a6e76b"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "a366871331644ed097476ceaec9fc0166124b56740b2d9ead177eb015799cc6a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.10+0/aws_c_http.v0.10.10.aarch64-linux-musl.tar.gz"
[[aws_c_http]]
arch = "aarch64"
git-tree-sha1 = "723e09765affa0d15e3e6188ee72f2335413edd8"
os = "freebsd"

    [[aws_c_http.download]]
    sha256 = "d4f55700440b83ca936130bfa93c1f0342f647f8a1330ce859a0cff451a6e344"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.10+0/aws_c_http.v0.10.10.aarch64-unknown-freebsd.tar.gz"
[[aws_c_http]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "30b18fb8838e493ef200f19de537be8b5b88596d"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "ec94e9cfe92931dae65d7cf0bd391400566e1b1715bead9098ecd32506ecdbfb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.10+0/aws_c_http.v0.10.10.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_http]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b06f169b166449deb760e5ccff4f90de24a19210"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "69165cb81fc3ddb131ca79998ba0bd3a60d61316c4e58646fa2920b707fa2979"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.10+0/aws_c_http.v0.10.10.armv6l-linux-musleabihf.tar.gz"
[[aws_c_http]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "82b73595c4bf8598758ee75d04b8696ff4fda0d3"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "7475da146de5c3296439ced0dbf28ae5e7749a9c8a14aac52e549e475c08138a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.10+0/aws_c_http.v0.10.10.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_http]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d9d7d1c437aa735e85402ccd47cf032555b04ee2"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "b6bd3242a9a962485f7a3c2b4652bd6d6d105b3d136a01e5b7e8e15fa680038f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.10+0/aws_c_http.v0.10.10.armv7l-linux-musleabihf.tar.gz"
[[aws_c_http]]
arch = "i686"
git-tree-sha1 = "34d092d6bbba6697c29ac03d0f97118322317953"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "d8ac8c6a43ea8e587d6baef28c439dd72191b533d4e3acf09c157ad6ffd4102c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.10+0/aws_c_http.v0.10.10.i686-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "i686"
git-tree-sha1 = "98828d895031ffae9bcc763ca5f7c90e0a989c1d"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "93109928b916f3ec57a704d2a03b1ec32e373aca17b7fcde8b5307dcc2851760"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.10+0/aws_c_http.v0.10.10.i686-linux-musl.tar.gz"
[[aws_c_http]]
arch = "powerpc64le"
git-tree-sha1 = "58005cd8950d82eec67d1e1f5699feebbba8ce52"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "163e426c11ec42fc5b315a8f56dfcd769cd857a11a9937cdf57e4122edb5d6b0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.10+0/aws_c_http.v0.10.10.powerpc64le-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "riscv64"
git-tree-sha1 = "7a2f52bc9f6ece0a2c72b5a6914c2a46d435592e"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "771c4e0b53958fad1587edf44093d9bf0aa64af87eca385b6cd7244fa57cc91e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.10+0/aws_c_http.v0.10.10.riscv64-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "aaf89743e2b408e0341d80b32612718b8a6a3da9"
os = "macos"

    [[aws_c_http.download]]
    sha256 = "6b7f3d8c4a747c6e7f65e0ddf0cf681eb50184832200a383791bad3a6d7ff464"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.10+0/aws_c_http.v0.10.10.x86_64-apple-darwin.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "d15368157c867d705446b3a42ec268314c1cfbdd"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "a791cad677b389e5ce450d55d2c413715ec946d2d4b0c6b2e285db3dac941ffa"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.10+0/aws_c_http.v0.10.10.x86_64-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "ba4b113c0f034abbdf6a5320aaf8919dd24c799e"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "daf1609e01d638ff6f9e69e5bd3b056a5a7b211636358aa71842606dbe7b9435"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.10+0/aws_c_http.v0.10.10.x86_64-linux-musl.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "295bc40ee017339263f316ef72bf0f187e48da9f"
os = "freebsd"

    [[aws_c_http.download]]
    sha256 = "5c5219a3c808a529b1e7ba4c3da99c23405de63b58b85713b419272f1b8453f9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.10+0/aws_c_http.v0.10.10.x86_64-unknown-freebsd.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "b9f09192dd8c023606fb9e3294fc7fef5418794c"
os = "windows"

    [[aws_c_http.download]]
    sha256 = "7d37898f9038d4a488c724f7369085734ee911ecaeaa9a10c334c6ca4e79bbd5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.10+0/aws_c_http.v0.10.10.x86_64-w64-mingw32.tar.gz"
