[[aws_c_http]]
arch = "aarch64"
git-tree-sha1 = "d0f33d58d5a96dab4a8d0ea1731ec1f12cc1ba96"
os = "macos"

    [[aws_c_http.download]]
    sha256 = "a6c62ebfba998607ab67b70da7b8be3240a231cf673ef9db1a4ec860338951d3"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.9+1/aws_c_http.v0.10.9.aarch64-apple-darwin.tar.gz"
[[aws_c_http]]
arch = "aarch64"
git-tree-sha1 = "6f79e6fdadaa20511281edd9deab03e28e60ae84"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "fa19066d84fc2833cd33c4951c1ee2afbde28fa53725e1aac9efd7cc1fea754b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.9+1/aws_c_http.v0.10.9.aarch64-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "aarch64"
git-tree-sha1 = "f322f597ba003a2d4a96813e12b8fdff77b68391"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "e19321ef176a701d35a870fb224763feaefab2eeb36b2922036f0605760d32e7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.9+1/aws_c_http.v0.10.9.aarch64-linux-musl.tar.gz"
[[aws_c_http]]
arch = "aarch64"
git-tree-sha1 = "8d85e95c2f6bb280e99e1d6c39ff8713b545bf11"
os = "freebsd"

    [[aws_c_http.download]]
    sha256 = "c278bba4eefb35daba9e14a85ae2c4c9f8c4af8a73c7dbaa96fb6e14341db9c6"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.9+1/aws_c_http.v0.10.9.aarch64-unknown-freebsd.tar.gz"
[[aws_c_http]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1769457a0e941dcb2c864fbb06153f1b5aacb6ca"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "eaa777cdc48e15000c88fe4b4aefc0be5cfb991aa867aef17a980741171e7edc"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.9+1/aws_c_http.v0.10.9.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_http]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bbdc261a04d1360f8acdedee6cc86f4a952b53be"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "783ac5ae6ebb95b1835c3caf56aeb95713603eb1ce2ecba4cdf56a654cb91f76"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.9+1/aws_c_http.v0.10.9.armv6l-linux-musleabihf.tar.gz"
[[aws_c_http]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "517f4304d32b4421b6c28f654e59a3bb0f23580a"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "ac68844e4401addac035e1a25e16157edec6eafdcf4b440e768f985df1596b20"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.9+1/aws_c_http.v0.10.9.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_http]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a506ed5b4c6a98266c8b79ee4232aac897acf04f"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "96d7bbd718cd5775257ed023493f0785d1c47b6326379d36f842327555ea6dd5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.9+1/aws_c_http.v0.10.9.armv7l-linux-musleabihf.tar.gz"
[[aws_c_http]]
arch = "i686"
git-tree-sha1 = "3ac721de61162d039cedf0f4ae7ac566e47a1397"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "378f8edd2a2a4678cf8fba010d4a5984526159b1e9a901d1637bffe28462a86e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.9+1/aws_c_http.v0.10.9.i686-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "i686"
git-tree-sha1 = "3a8a35545153c506b66e021034fd426b17a933c9"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "b6c0e00614586daab1266349e1dc66b3bed833cc553d06ab41bf692eed8f52a8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.9+1/aws_c_http.v0.10.9.i686-linux-musl.tar.gz"
[[aws_c_http]]
arch = "powerpc64le"
git-tree-sha1 = "eb7bfe0c06d95bb1fcc3d9a9aedc1b27c776b517"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "9964627510107b8f1415ac5bad61b11f1c682d07d74cc651481497ba35b563e5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.9+1/aws_c_http.v0.10.9.powerpc64le-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "riscv64"
git-tree-sha1 = "6935b94ec6f7f88ce9fab75b99f173f9aeb35407"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "68f2c90d8a677e0db4ba960fb3654addc0089fac0bad88145bad12a8bc774ef7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.9+1/aws_c_http.v0.10.9.riscv64-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "328951766d568b5708342660f559d2322fe73355"
os = "macos"

    [[aws_c_http.download]]
    sha256 = "5327d57fcd7483fd87e3d79a90063d5dc33c211f83423c7a4927be6dda1e4e08"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.9+1/aws_c_http.v0.10.9.x86_64-apple-darwin.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "92a45cf703300e241ec7cde8b67b49510efe58de"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "9cc5c096f848da9285e0524ff5ed8ab6143579baafd2f68812c14550d99735bd"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.9+1/aws_c_http.v0.10.9.x86_64-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "d26dab9a59e7811dbea130be2771a95b79d58390"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "556ae1860aa4d0c772f531c5ce07d19685aa70b67613600f5f006a508f45d674"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.9+1/aws_c_http.v0.10.9.x86_64-linux-musl.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "7c11a57239e5b44d2eed472d7e25de8f6c245b03"
os = "freebsd"

    [[aws_c_http.download]]
    sha256 = "686e84263e9b77c28c9778a8922981113b8a3fad2b9acd5983176a3f5a5863e8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.9+1/aws_c_http.v0.10.9.x86_64-unknown-freebsd.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "98abd0cf5aae7b6c95eba649964554eb330e69b7"
os = "windows"

    [[aws_c_http.download]]
    sha256 = "50ac119454fb7f8315859bfd894420947ae341af3ce79a40eca1b28bfd806d25"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.9+1/aws_c_http.v0.10.9.x86_64-w64-mingw32.tar.gz"
